version: "3.9"

services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_PASSWORD: ${PSQL_PASSWORD}
            POSTGRES_DB: ${PSQL_DATABASE}
    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DESIGN: dracula
        ports:
            - 3333:3333
