version: "3.9"

services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: greenlight
    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DESIGN: dracula
        ports:
            - 3333:3333
